# Generated by Django 5.1 on 2024-08-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rateyourcompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Companyname', models.CharField(max_length=200)),
                ('Jobtitle', models.CharField(max_length=200)),
                ('overallrating', models.IntegerField(default=0)),
                ('worklifebalance', models.IntegerField(default=0)),
                ('salaryandbenefits', models.IntegerField(default=0)),
                ('promostion', models.IntegerField(default=0)),
                ('jobsecurity', models.IntegerField(default=0)),
                ('skilldevelopment', models.IntegerField(default=0)),
                ('worksatisfation', models.IntegerField(default=0)),
                ('companyculture', models.IntegerField(default=0)),
                ('companylikes', models.TextField(max_length=300)),
                ('companydislikes', models.TextField(max_length=300)),
                ('male', models.BooleanField(default=False)),
                ('female', models.BooleanField(default=False)),
                ('prefernottosay', models.BooleanField(default=False)),
                ('workfromhome', models.BooleanField(default=False)),
                ('office', models.BooleanField(default=False)),
                ('hybrid', models.BooleanField(default=False)),
                ('currentlyworkingyes', models.BooleanField(default=False)),
                ('No', models.BooleanField(default=False)),
                ('selectemploymenttype', models.CharField(choices=[('Fulltime', 'Fulltime'), ('Parttime', 'Parttime'), ('Contractual', 'Contractual'), ('Inter', 'Inter'), ('Freelancer', 'Freelancer')], max_length=20)),
                ('deperment', models.TextField(max_length=200)),
            ],
        ),
    ]
