# Generated by Django 5.1 on 2024-08-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abisionapp', '0004_alter_emailsignup_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsignup',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email Address'),
        ),
    ]
