# Generated by Django 5.1 on 2024-08-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abisionapp', '0005_alter_emailsignup_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsignup',
            name='Email',
            field=models.EmailField(max_length=200),
        ),
    ]
