# Generated by Django 5.1 on 2024-08-28 05:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abisionapp', '0007_designations'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupFinish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=200)),
                ('Lastname', models.CharField(max_length=200)),
                ('Designation', models.CharField(max_length=200)),
                ('Mobile', models.IntegerField(validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)])),
                ('Companyname', models.CharField(max_length=200)),
                ('Companywebsite', models.URLField()),
            ],
        ),
    ]
