# Generated by Django 5.1 on 2024-08-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abisionapp', '0008_signupfinish'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otpverifiction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Inputotp', models.IntegerField()),
            ],
        ),
    ]
