# Generated by Django 5.1 on 2024-09-20 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abisionapp', '0012_signupfinish_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signupfinish',
            name='User',
        ),
    ]
