# Generated by Django 5.1 on 2024-09-25 10:40

import abisionapp.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abisionapp', '0019_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'rtf', 'pdf']), abisionapp.models.validate_file_size]),
        ),
    ]
