# Generated by Django 5.1 on 2024-09-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abisionapp', '0024_alter_resume_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
