# Generated by Django 5.1 on 2024-09-26 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abisionapp', '0025_alter_resume_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='user',
        ),
    ]
