# Generated by Django 5.1 on 2024-10-09 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abisionapp', '0030_keyskills'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_employment', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full time'), ('internship', 'Internship')], default='full_time', max_length=10)),
                ('years_of_experience', models.IntegerField(default=0)),
                ('months_of_experience', models.IntegerField(default=0)),
                ('current_company', models.CharField(max_length=100)),
                ('current_job', models.CharField(max_length=100)),
                ('years_of_Joining', models.IntegerField(default=0)),
                ('months_of_Joining', models.IntegerField(default=0)),
                ('Current_salary', models.IntegerField(default=0)),
                ('skill_used', models.CharField(max_length=50)),
                ('Job_prfile', models.CharField(max_length=4000)),
                ('Notice_period', models.CharField(max_length=100)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
