# Generated by Django 5.1 on 2024-10-11 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abisionapp', '0031_employment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employment',
            name='months_of_Joining',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employment',
            name='months_of_experience',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employment',
            name='years_of_experience',
            field=models.CharField(max_length=50),
        ),
    ]
