# Generated by Django 5.1 on 2024-10-12 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abisionapp', '0032_alter_employment_months_of_joining_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_education', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('specialixation', models.CharField(max_length=100)),
                ('course_type', models.CharField(choices=[('FT', 'Full time'), ('PT', 'Part time'), ('C', 'Correspondence/Distance learning')], default='FT', max_length=2)),
                ('startingyear_of_course', models.CharField(max_length=100)),
                ('endingyear_of_course', models.CharField(max_length=100)),
                ('grading_system', models.CharField(max_length=100)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
