# Generated by Django 5.1 on 2024-10-12 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abisionapp', '0033_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='course_type',
            field=models.CharField(choices=[('FULL_TIME', 'Full time'), ('PART_TIME', 'Part time'), ('CORRESPONDENCE', 'Correspondence/Distance learning')], default='FULL_TIME', max_length=50),
        ),
    ]
