# Generated by Django 5.1 on 2024-10-14 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abisionapp', '0037_project_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='employment_type',
            new_name='employment_type_project',
        ),
    ]
