# Generated by Django 5.1 on 2024-10-19 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abisionapp', '0040_career_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender_type_project', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Transgender', 'Transgender')], max_length=50)),
                ('Marital_type_project', models.CharField(choices=[('Single/unmarried', 'Single/unmarried'), ('Married', 'Married'), ('Widowed', 'Widowed'), ('Divorced', 'Divorced'), ('Separated', 'Separated'), ('Other', 'Other')], max_length=50)),
                ('date', models.CharField(max_length=100)),
                ('month', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('differently_abled_type_career', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('career_break_type_career', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=50)),
                ('permanent_address', models.CharField(max_length=100)),
                ('hometown', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=100)),
            ],
        ),
    ]
