# Generated by Django 5.1 on 2024-10-19 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abisionapp', '0041_personal_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_details',
            name='Marital_type_project',
            field=models.CharField(choices=[('Single', 'Single/unmarried'), ('Married', 'Married'), ('Widowed', 'Widowed'), ('Divorced', 'Divorced'), ('Separated', 'Separated'), ('Other', 'Other')], max_length=50),
        ),
    ]
