# Generated by Django 5.1 on 2024-10-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abisionapp', '0044_notification_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('accepted', 'Accepted')], default='requested', max_length=10),
        ),
    ]
