# Generated by Django 5.1 on 2024-10-31 05:38

import abisionapp.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abisionapp', '0045_follow_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('workplace', models.CharField(max_length=50)),
                ('job_location', models.CharField(max_length=255)),
                ('job_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('skills', models.TextField()),
                ('identify_source', models.CharField(max_length=50)),
                ('additional_info', models.TextField()),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=255)),
                ('applicant_email', models.EmailField(max_length=254)),
                ('applicant_resume', models.FileField(blank=True, null=True, upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'rtf', 'pdf']), abisionapp.models.validate_file_size])),
                ('answers', models.ManyToManyField(to='abisionapp.answer')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abisionapp.jobposting')),
            ],
        ),
        migrations.CreateModel(
            name='JobQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('must_have', models.BooleanField(default=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abisionapp.jobposting')),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abisionapp.qualification')),
            ],
        ),
        migrations.AddField(
            model_name='jobposting',
            name='qualifications',
            field=models.ManyToManyField(through='abisionapp.JobQualification', to='abisionapp.qualification'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abisionapp.qualification'),
        ),
    ]
