# Generated by Django 5.1 on 2024-10-31 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abisionapp', '0046_answer_qualification_jobposting_jobapplication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='additional_info',
            field=models.CharField(max_length=100),
        ),
    ]
