# Generated by Django 5.1 on 2024-11-14 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abisionapp', '0049_alter_jobapplication_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualification',
            name='answer_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('dropdown', 'Dropdown'), ('boolean', 'Yes/No')], default='text', max_length=50),
        ),
        migrations.AddField(
            model_name='qualification',
            name='dropdown_options',
            field=models.TextField(blank=True, null=True),
        ),
    ]
