# Generated by Django 5.1 on 2024-11-15 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abisionapp', '0052_alter_qualification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualification',
            name='ideal_answer',
            field=models.TextField(default='No ideal answer provided'),
        ),
    ]
